### ISSUE TITLE
Missing Logo in the main page of MediaWiki APB

### ISSUE THREAD

**Issue by johnkim76** [fusor/apb-examples#59]
The logo is missing in the main page of the MediaWiki APB.  Verified that it was missing in the RHCC via Catasb
![mediawiki](https://user-images.githubusercontent.com/2566892/27504733-d1af4df6-585d-11e7-843d-be10b079b4c3.jpg)

**Comment by jmontleon** [comment]
This is the default behavior until the user sets it.

**Comment by jwmatthews** [comment]
@jmontleon thanks for clarifying.

**Comment by jwmatthews** [comment]
Closing this issue as the missing logo message is expected behavior.
